import type { MarketEventDef } from "@/types";

/**
 * The market event catalog — every obstacle in CRYPTO FLOW is one of these.
 *
 * Design rules:
 * - Tier 1 events teach the verb; generous rewards, soft penalties.
 * - Tier 2 events mix verbs and raise stakes.
 * - Tier 3 events are run-defining: big portfolio swings both ways.
 * - Rewards/penalties are tuned so a clean player compounds ~+5%/event
 *   while a sloppy player bleeds toward the bear.
 */
export const MARKET_EVENTS: readonly MarketEventDef[] = [
  // ——— Tier 1 ———
  {
    id: "whale-buy",
    title: "Whale Buy",
    description: "A whale sweeps the order book. Ride the green candle up.",
    tier: 1,
    bestAction: "jump",
    glyph: "◆",
    tint: 0x4cc38a,
    momentumReward: 9,
    momentumPenalty: 10,
    portfolioReward: 0.05,
    portfolioPenalty: 0.04,
    score: 120,
    sound: "surge",
  },
  {
    id: "protocol-hack",
    title: "Protocol Hack",
    description: "Exploit in the wild. Get under the falling price.",
    tier: 1,
    bestAction: "slide",
    glyph: "▲",
    tint: 0xe2565c,
    momentumReward: 9,
    momentumPenalty: 10,
    portfolioReward: 0.04,
    portfolioPenalty: 0.05,
    score: 120,
    sound: "alarm",
  },
  {
    id: "airdrop",
    title: "Airdrop",
    description: "Free tokens raining down. Rise to claim them.",
    tier: 1,
    bestAction: "jump",
    glyph: "✦",
    tint: 0xe8a33d,
    momentumReward: 8,
    momentumPenalty: 8,
    portfolioReward: 0.06,
    portfolioPenalty: 0.02,
    score: 100,
    sound: "chime",
  },
  {
    id: "gas-spike",
    title: "Gas Spike",
    description: "Fees explode. Duck under the surge.",
    tier: 1,
    bestAction: "slide",
    glyph: "≋",
    tint: 0x7f9cf5,
    momentumReward: 8,
    momentumPenalty: 9,
    portfolioReward: 0.03,
    portfolioPenalty: 0.03,
    score: 100,
    sound: "glitch",
  },
  // ——— Tier 2 ———
  {
    id: "bridge-exploit",
    title: "Bridge Exploit",
    description: "The bridge is compromised. Exit your position, now.",
    tier: 2,
    bestAction: "exit",
    glyph: "⛝",
    tint: 0xe2565c,
    momentumReward: 12,
    momentumPenalty: 14,
    portfolioReward: 0.05,
    portfolioPenalty: 0.09,
    score: 220,
    sound: "alarm",
  },
  {
    id: "etf-approval",
    title: "ETF Approval",
    description: "Institutions are in. Rotate into the inflow.",
    tier: 2,
    bestAction: "rotate",
    glyph: "◈",
    tint: 0x4cc38a,
    momentumReward: 12,
    momentumPenalty: 12,
    portfolioReward: 0.09,
    portfolioPenalty: 0.05,
    score: 220,
    sound: "surge",
  },
  {
    id: "token-unlock",
    title: "Token Unlock",
    description: "Vesting cliff hits. Exit before the dump lands.",
    tier: 2,
    bestAction: "exit",
    glyph: "⬡",
    tint: 0xc084fc,
    momentumReward: 11,
    momentumPenalty: 13,
    portfolioReward: 0.05,
    portfolioPenalty: 0.08,
    score: 200,
    sound: "glitch",
  },
  {
    id: "governance-vote",
    title: "Governance Vote",
    description: "Proposal passing. Rotate to the winning side.",
    tier: 2,
    bestAction: "rotate",
    glyph: "▣",
    tint: 0x38bdf8,
    momentumReward: 11,
    momentumPenalty: 12,
    portfolioReward: 0.06,
    portfolioPenalty: 0.06,
    score: 200,
    sound: "chime",
  },
  {
    id: "protocol-upgrade",
    title: "Protocol Upgrade",
    description: "Hard fork ahead. Vault over the migration.",
    tier: 2,
    bestAction: "jump",
    glyph: "⇪",
    tint: 0x7f9cf5,
    momentumReward: 11,
    momentumPenalty: 12,
    portfolioReward: 0.06,
    portfolioPenalty: 0.06,
    score: 200,
    sound: "surge",
  },
  // ——— Tier 3 ———
  {
    id: "exchange-hack",
    title: "Exchange Hack",
    description: "Hot wallets drained. Get out before withdrawals freeze.",
    tier: 3,
    bestAction: "exit",
    glyph: "☒",
    tint: 0xe2565c,
    momentumReward: 16,
    momentumPenalty: 20,
    portfolioReward: 0.08,
    portfolioPenalty: 0.14,
    score: 400,
    sound: "alarm",
  },
  {
    id: "liquidation-cascade",
    title: "Liquidation Cascade",
    description: "Leverage unwinding violently. Slide beneath the wicks.",
    tier: 3,
    bestAction: "slide",
    glyph: "▼",
    tint: 0xe2565c,
    momentumReward: 16,
    momentumPenalty: 20,
    portfolioReward: 0.08,
    portfolioPenalty: 0.13,
    score: 400,
    sound: "glitch",
  },
  {
    id: "stablecoin-depeg",
    title: "Stablecoin Depeg",
    description: "The peg is slipping. Rotate to hard money.",
    tier: 3,
    bestAction: "rotate",
    glyph: "≠",
    tint: 0xc084fc,
    momentumReward: 15,
    momentumPenalty: 18,
    portfolioReward: 0.10,
    portfolioPenalty: 0.12,
    score: 380,
    sound: "alarm",
  },
  {
    id: "flash-crash",
    title: "Flash Crash",
    description: "The floor vanishes for a heartbeat. Leap the gap.",
    tier: 3,
    bestAction: "jump",
    glyph: "⚡",
    tint: 0xe8a33d,
    momentumReward: 15,
    momentumPenalty: 18,
    portfolioReward: 0.09,
    portfolioPenalty: 0.12,
    score: 380,
    sound: "glitch",
  },
] as const;

export function eventById(id: string): MarketEventDef | undefined {
  return MARKET_EVENTS.find((e) => e.id === id);
}
